services:
  frontend:
    ports:
      - '8082:80'
    build:
      context: .
      dockerfile: ./Frontend/Dockerfile
    volumes:
      - ./Frontend/src:/app/src:delegated
    networks:
      - local_network
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./Backend/Dockerfile
    ports:
      - '9092:80'
    environment:
      - ConnectionStrings__AppDb=Data Source=./db.sqlite

networks:
  local_network:
    driver: bridge
